#!/bin/bash

set -o nounset # script exits when tries to use undeclared variables == set -u
set -o pipefail # causes pipelines to retain / set the last non-zero status

default_branch=${BUILDKITE_PLUGIN_ATLAS_DEFAULT_BRANCH:-${BUILDKITE_PIPELINE_DEFAULT_BRANCH}}
dev_url=${BUILDKITE_PLUGIN_ATLAS_DEV_URL}
project=${BUILDKITE_PLUGIN_ATLAS_PROJECT}
apply_env=${BUILDKITE_PLUGIN_APPLY_ENV:-"turso"}
atlas_config=${BUILDKITE_PLUGIN_ATLAS_CONFIG:-"file://atlas.hcl"}
dir=${BUILDKITE_PLUGIN_ATLAS_DIR}
step=${BUILDKITE_PLUGIN_ATLAS_STEP:-lint}
debug=${BUILDKITE_PLUGIN_ATLAS_DEBUG:-false}

atlas_context=$(cat <<EOF
{
    "branch": "$BUILDKITE_BRANCH",
    "commit": "$BUILDKITE_COMMIT"
}
EOF
)

if [[ "$debug" == "true" ]]; then
    set -o xtrace # trace what's executed == set -x (useful for debugging)
fi

function main() {
    local error_results=
    local warning_results=
    local url=

    # Lint and Validate
    if [ "${step}" = "lint" ] || [ "${step}" = "all" ]; then
        echo +++ :database: lint and validate

        lint_result_file=$(mktemp)
        # Run the lint command with the web client, and output to json
        lint_result=$(atlas migrate lint --dev-url "${dev_url}" --dir "${dir}" -w --format "{{ json .  }}" --context "${atlas_context}" > "$lint_result_file" 2>&1)

        # Parse the results to display on the top of the buildkite job
        lint_result_file="$lint_result_file" parse_lint_result

        # Start the annotation
        echo -e "\`atlas migrate lint\` results: " | buildkite-agent annotate --context atlas

        # Check for error results, warning results, otherwise it was successful
        if [[ "$error_results" != "" && "$error_results" != "null" ]]; then
            result=1
            echo -e  ":scream_cat: errors found\n" | buildkite-agent annotate --context "atlas" --style "error" --append
            echo -e  "**Errors**:\n" | buildkite-agent annotate --context "atlas" --append
            echo -e "$(echo "$error_results" |jq -r '"Position | Text | Code", "---| --- |----", (.[] | "\(.Pos) | \(.Text)| \(.Code)" )')\n\n" | buildkite-agent annotate --context "atlas" --append
            if [[ "$warning_results" != ""&& "$warning_results" != "null" ]]; then
            echo -e  "**Warnings**:\n" | buildkite-agent annotate --context "atlas" --append
            echo -e "$(echo "$warning_results" |jq -r '"Position | Text | Code", "---| --- |----", (.[] | "\(.Pos) | \(.Text)| \(.Code)" )')\n\n" | buildkite-agent annotate --context "atlas" --append
            fi
        elif [[ "$warning_results" != "" && "$warning_results" != "null" ]]; then
            # do not error on warnings
            result=0
            echo -e  ":smirk_cat: warnings found\n" | buildkite-agent annotate --context "atlas" --style "warning" --append
            echo -e  "**Warnings**:\n" | buildkite-agent annotate --context "atlas" --append
            echo -e "$(echo "$warning_results" |jq -r '"Position | Text | Code", "---| --- |----", (.[] | "\(.Pos) | \(.Text)| \(.Code)" )')\n\n" | buildkite-agent annotate --context "atlas" --append
        else
            result=0
            echo -e  ":heart_eyes_cat: no errors found, congrats!\n"| buildkite-agent annotate --context "atlas" --style "success"  --append
        fi

        echo -e  "See the full report [here]($url)\n" | buildkite-agent annotate --context "atlas" --append

        # Exit early if this failed
        if [[ $result -ne 0 ]]; then
            exit "$result"
        fi

        # Run validate and exit early, if failed
        atlas migrate validate --dev-url "${dev_url}" --dir "${dir}"
        result=$?
        if [[ $result -ne 0 ]]; then
            exit "$result"
        fi
    fi

    # Push the migration if the step was enabled
    if [ "${step}" = "migrate" ] || [ "${step}" = "all" ]; then
        echo +++ :rocket: push migrations
        # only push on the default branch
        if [ "${BUILDKITE_BRANCH}" = "${default_branch}" ]; then
            atlas migrate push "${project}" --dev-url "${dev_url}" --dir "${dir}" --context "${atlas_context}"
            result=$?
        else
            echo not pushing migration, not running against "${default_branch}" branch
            result=0
        fi
    fi

    # Apply the migration if the step was enabled
    if [ "${step}" = "apply" ] || [ "${step}" = "all" ]; then
        echo +++ :shipit: apply migrations
        # only apply on the default branch
        if [ "${BUILDKITE_BRANCH}" = "${default_branch}" ]; then
            atlas migrate apply --env "${apply_env}" --config "${atlas_config}"
            result=$?
        else
            echo not apply migration, not running against "${default_branch}" branch
            result=0
        fi
    fi

    rm -f "$lint_result_file"

    exit "$result"
}


function parse_lint_result () {
    url=$(jq -r '.URL' "$lint_result_file")

    num_files=$(jq '.Files | length' "$lint_result_file")

    # There are no files present on a successful run, abort now
    if [[ $num_files == 0 ]]; then
        return
    fi

    error_results=$(jq '.Files[0]
    | select(.Reports != null)
    | .Reports
    | map(select(.Text == "destructive changes detected"))
    | .[0].Diagnostics' "$lint_result_file")

    warning_results=$(jq '.Files[0]
    | select(.Reports != null)
    | .Reports
    | map(select(.Text == "data dependent changes detected"))
    | .[0].Diagnostics' "$lint_result_file")

    # Display these in the logs
    echo "$warning_results" |jq
    echo "$error_results" |jq
}

main